trigger:
  branches:
    include:
      - main  # Or 'master' or any other branch

pool:
  vmImage: 'ubuntu-latest'

variables:
  azureSubscription: 'MyAzureServiceConnection' # Change to your service connection name
  appName: 'my-webapp-name'                    # Change to your Azure Web App name
  environment: 'Production'

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '18.x'  # Use appropriate version
    displayName: 'Install Node.js'

  - script: |
      npm install
      npm run build
    displayName: 'Install dependencies and build'

  - script: npm test
    displayName: 'Run Tests'

  - task: ArchiveFiles@2
    inputs:
      rootFolderOrFile: '$(System.DefaultWorkingDirectory)'
      includeRootFolder: false
      archiveType: 'zip'
      archiveFile: '$(Build.ArtifactStagingDirectory)/webapp.zip'
      replaceExistingArchive: true
    displayName: 'Archive files'

  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: '$(Build.ArtifactStagingDirectory)/webapp.zip'
      ArtifactName: 'drop'
    displayName: 'Publish Artifact'

  - task: AzureWebApp@1
    inputs:
      azureSubscription: '$(azureSubscription)'
      appName: '$(appName)'
      package: '$(Build.ArtifactStagingDirectory)/webapp.zip'
    displayName: 'Deploy to Azure Web App'
